# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e216ace6518f1c51762da34a8ea2c61f519b4c3f921fbb636b1b79254ced6b1921726f476a54c934c8a79818c8359f2545a100c254fd9899793f6b10c4d79d4

test:
  secret_key_base: 8ccd4b8a21700386daf5fadd0ce38abb5ddb449bbc048fefc78fefa78ed1be53d11c9d4b5e14a8e1c36b15188a6fc8a59ada3d954cd279ebf5cd17cce70c3571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
